## Fazendo o KNN usando numpy e pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
# temos 2 vetores e queremos saber a distancia euclidiana entre eles
x_vetor = np.array([5,7,9])
y_vetor = np.array([5,5,5])

    # Qual a fórmula da distãncia euclidiana?

$$DE (x,y) = \sqrt{\sum_{i}^{p}(x_{i}-y_{i})^{2} }$$

DE = Distancia Euclidiana

    # Como fazer a subtração de cada posição do vetor (iteração)?

$(x_{i}-y_{i})$

$(x_{0}-y_{0}) = (5-5)$

$(x_{1}-y_{1}) = (7-5)$

$(x_{2}-y_{2}) = (9-5)$

In [7]:
# subtração de cada posição do vetor
de = x_vetor - y_vetor
de

array([0, 2, 4])

    # Como elevar ao quadrado cada valor?
   
$(x_{i}-y_{i})^{2}$

$(0)^{2}$

$(2)^{2}$

$(5)^{2}$

In [8]:
# elevação ao quadrado
de = de**2
de

array([ 0,  4, 16])

        # Como fazer o somatório dos elementos?
$(0) + (4) + (16) = (?)$

In [15]:
# somatório dos elementos
de = de.sum()
de

20

        # Como tirar a raiz quadrada?
$\sqrt{(20)} = 4.47...$

In [16]:
de = np.sqrt(de)
de

4.4721359549995796

## Exemplo usando Pandas DataFrame

In [18]:
# construindo o DataFrame
# rotulos y
filmes = np.array(['Invocacao do Mal','Floresta Maldita','Meu Passado Me Condena', 'Vizinhos 2', 'Deadpool', 'Tirando o Atraso'])
filmes

array(['Invocacao do Mal', 'Floresta Maldita', 'Meu Passado Me Condena',
       'Vizinhos 2', 'Deadpool', 'Tirando o Atraso'],
      dtype='<U22')

In [20]:
# rotulos x
tipos = np.array(['Violencia', 'Romance', 'Acao', 'Comedia'])
tipos

array(['Violencia', 'Romance', 'Acao', 'Comedia'],
      dtype='<U9')

In [33]:
# valores dos atributos
valores = np.array([[0.6,0.0,0.3,0.0],
                    [0.9,0.0,0.5,0.1],
                    [0.1,0.2,0.1,0.9],
                    [0.0,0.1,0.2,0.8],
                    [0.5,0.0,0.7,0.1],
                    [0.0,0.2,0.2,0.8]])
valores

array([[ 0.6,  0. ,  0.3,  0. ],
       [ 0.9,  0. ,  0.5,  0.1],
       [ 0.1,  0.2,  0.1,  0.9],
       [ 0. ,  0.1,  0.2,  0.8],
       [ 0.5,  0. ,  0.7,  0.1],
       [ 0. ,  0.2,  0.2,  0.8]])

In [38]:
df = pd.DataFrame(data=valores, columns=tipos, index=filmes)
df

Violencia  Romance  Acao  Comedia
Invocacao do Mal              0.6      0.0   0.3      0.0
Floresta Maldita              0.9      0.0   0.5      0.1
Meu Passado Me Condena        0.1      0.2   0.1      0.9
Vizinhos 2                    0.0      0.1   0.2      0.8
Deadpool                      0.5      0.0   0.7      0.1
Tirando o Atraso              0.0      0.2   0.2      0.8

In [41]:
# Floresta Maldita vs. Invovacao do Mal
df.iloc[1] - df.iloc[0]

Violencia    0.3
Romance      0.0
Acao         0.2
Comedia      0.1
dtype: float64

In [42]:
# Floresta Maldita vs. Invocacao do Mal
df.iloc[1] - df.iloc[5]

Violencia    0.9
Romance     -0.2
Acao         0.3
Comedia     -0.7
dtype: float64

In [43]:
!jupyter notebook --generate-config

Writing default config to: /Users/gilbertofilho/.jupyter/jupyter_notebook_config.py
